### ISSUE TITLE
Pin tab status doesn't show correctly

### ISSUE THREAD

**Issue by benyaminl** [carlosdoub/tab_list_button_enhanced#3]
Pin status doesn't show correctly if tab is pinned or not
Also on context menu of the extension

Pin button
![image](https://user-images.githubusercontent.com/2817332/123421677-5aa73000-d5e7-11eb-8f87-be3db14d7f0d.png)

Context menu
![image](https://user-images.githubusercontent.com/2817332/123421711-6a267900-d5e7-11eb-89ac-8137e79d5609.png)

**Comment by carlosdoub** [comment]
The pin button or menu wasn't suppose to show the status of the tab...

**Comment by benyaminl** [comment]
> 
> 
> The pin button or menu wasn't suppose to show the status of the tab...

If I implement it, is it okay?

Because I use your extension as replacement of tab bar as I remove/hide tab bar using userChrome.css 😂

**Comment by carlosdoub** [comment]
Haha. Go ahead, thanks
